service: plane-bot
frameworkVersion: "3"
configValidationMode: warn

# plugins:
#   - serverless-webpack
# custom:
#   webpack:
#     webpackConfig: "webpack.config.js"
#     includeModules: true

provider:
  name: aws
  stage: dev
  region: us-east-1
  profile: AWS-MES
  runtime: nodejs14.x
  httpApi:
    cors: true

functions:
  main:
    handler: build/lambdas/main.handler
    memorySize: 512
    timeout: 7
    events:
      - httpApi:
          method: POST
          path: /post/1
  capture:
    handler: build/lambdas/capture.handler
    memorySize: 1536
    timeout: 15
    events:
      - httpApi:
          method: GET
          path: /capture
    # layers:
    #   - arn: arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:25
